language: python
services:
  - postgresql
python:
  - "3.4"
cache: pip
install: "pip install -r requirements.txt"
before_script:
  - "python manage.py migrate"
  - "python manage.py collectstatic --noinput"
script: "python manage.py test"
