language: python
services:
  - postgresql
python:
  - "3.4"
cache: pip
install: "pip install -r requirements.txt"
before_script:
  - "python manage.py migrate"
  - "python manage.py collectstatic --noinput"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3" # give xvfb some time to start
script: "python manage.py test"
