proddb:
  image: postgres
  environment:
    - POSTGRES_USER=gissmo
    - POSTGRES_PASSWORD=gissmo
  ports:
    - "5433:5432"
prod:
  extends:
    file: common.yml
    service: webapp
  links:
    - db
  environment:
    - DJANGO_SETTINGS_MODULE=gissmo.settings.production
  env_file: production.env
