# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 13:58
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20160307_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Registration date')),
                ('private_link', models.URLField(blank=True, null=True, verbose_name='Private link')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Starting date')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Ending date')),
                ('_file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home/olivier/gissmo/eost_django_poc/upload'), upload_to='document/%Y/%m/%d/', verbose_name='File')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Type', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.GissmoUser'),
        ),
    ]
