# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 07:52
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='_file',
            field=models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='/home/olivier/gissmo/project/gissmo/upload'), upload_to='document/%Y/%m/%d/', verbose_name='File'),
        ),
    ]
