# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installation',
            name='configuration',
        ),
        migrations.AddField(
            model_name='installation',
            name='configurations',
            field=models.ManyToManyField(blank=True, to='equipment.Configuration'),
        ),
    ]
