# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
        ('grid', '0001_initial'),
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Site'),
        ),
        migrations.AddField(
            model_name='installation',
            name='built',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Built'),
        ),
        migrations.AddField(
            model_name='installation',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Configuration'),
        ),
        migrations.AddField(
            model_name='installation',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment'),
        ),
        migrations.AddField(
            model_name='installation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grid.Installation', verbose_name='Connected to'),
        ),
        migrations.AddField(
            model_name='channel',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.Installation'),
        ),
        migrations.AddField(
            model_name='channel',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.Network'),
        ),
    ]
