# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('grid', '0001_initial'),
        ('equipment', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Place'),
        ),
        migrations.AddField(
            model_name='station',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_state', to='grid.State'),
        ),
        migrations.AddField(
            model_name='state',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_grid.state_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='state',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_station', to='grid.Station'),
        ),
        migrations.AddField(
            model_name='installation',
            name='configurations',
            field=models.ManyToManyField(blank=True, to='equipment.Configuration'),
        ),
        migrations.AddField(
            model_name='installation',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipment.Equipment'),
        ),
        migrations.AddField(
            model_name='installation',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grid.Installation', verbose_name='Connected to'),
        ),
        migrations.AddField(
            model_name='installation',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Place'),
        ),
        migrations.AddField(
            model_name='channel',
            name='installation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.Installation'),
        ),
        migrations.AddField(
            model_name='channel',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grid.Network'),
        ),
    ]
