# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0002_auto_20160418_0752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datatype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='channel',
            name='datatype',
        ),
        migrations.AddField(
            model_name='channel',
            name='datatype',
            field=models.ManyToManyField(blank=True, to='grid.Datatype'),
        ),
    ]
