# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0003_auto_20160418_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='datatype',
            new_name='datatypes',
        ),
    ]
