# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('equipment', '0002_auto_20160304_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='documents',
            field=models.ManyToManyField(blank=True, to='document.Document'),
        ),
        migrations.AddField(
            model_name='model',
            name='documents',
            field=models.ManyToManyField(blank=True, to='document.Document'),
        ),
    ]
