INSERT INTO bdmateriel_evenementequip (description) VALUES ('Achat');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Connection');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Dégradation');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Départ prêt');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Départ SAV');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Départ mission');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Désinstallation');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Disparition');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Etalonnage');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Installation');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Maintenance');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Mise en obsolescence');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Panne');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Passage des tests');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Récupération');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Réforme');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Retour SAV');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Retour mission');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Retour prêt');
INSERT INTO bdmateriel_evenementequip (description) VALUES ('Vol');

