# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 15:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Built',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude (°)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude (°)')),
                ('elevation', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Elevation (m)')),
                ('latitude_datum', models.CharField(blank=True, default='WGS84', max_length=15, null=True, verbose_name='Latitude datum')),
                ('longitude_datum', models.CharField(blank=True, default='WGS84', max_length=15, null=True, verbose_name='Longitude datum')),
                ('name', models.CharField(default='Unknown', max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuiltType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Built type',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude (°)')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude (°)')),
                ('elevation', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='Elevation (m)')),
                ('latitude_datum', models.CharField(blank=True, default='WGS84', max_length=15, null=True, verbose_name='Latitude datum')),
                ('longitude_datum', models.CharField(blank=True, default='WGS84', max_length=15, null=True, verbose_name='Longitude datum')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('_type', models.IntegerField(choices=[(0, 'Observatory'), (1, 'Customer service place'), (2, 'Undefined'), (3, 'Other'), (4, 'Testing site'), (5, 'Theoritical site')], default=5, verbose_name='Type')),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Creation date')),
                ('address_street', models.CharField(blank=True, max_length=100, null=True, verbose_name='Street')),
                ('address_zipcode', models.CharField(blank=True, max_length=15, null=True, verbose_name='Zip code')),
                ('address_city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('address_region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('address_county', models.CharField(blank=True, max_length=100, null=True, verbose_name='District')),
                ('address_country', models.CharField(blank=True, max_length=50, null=True, verbose_name='Country')),
                ('geology', models.CharField(blank=True, max_length=50, null=True, verbose_name='Geological formation')),
                ('contact', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Site')),
            ],
        ),
        migrations.AddField(
            model_name='site',
            name='documents',
            field=models.ManyToManyField(blank=True, through='place.SiteDocument', to='document.Document'),
        ),
        migrations.AddField(
            model_name='site',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Organism'),
        ),
        migrations.AddField(
            model_name='site',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Site', verbose_name='Referent'),
        ),
        migrations.AddField(
            model_name='built',
            name='_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.BuiltType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='built',
            name='documents',
            field=models.ManyToManyField(blank=True, to='document.Document'),
        ),
        migrations.AddField(
            model_name='built',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Site'),
        ),
    ]
