# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(choices=[(0, 'Available'), (1, 'Testing'), (2, 'Ready'), (3, 'Running'), (4, 'Failure'), (5, 'Closed')], default=0)),
                ('start', models.DateTimeField(auto_now=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_place', to='place.Place')),
            ],
        ),
        migrations.AddField(
            model_name='place',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_state', to='place.State'),
        ),
    ]
