# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Player'),
        ),
        migrations.AddField(
            model_name='site',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='place.Site', verbose_name='Referent site'),
        ),
        migrations.AddField(
            model_name='site',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_state', to='place.State'),
        ),
        migrations.AddField(
            model_name='built',
            name='_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.BuiltType', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='built',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Site'),
        ),
    ]
