# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20160418_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
