#!/usr/bin/env python

import glob
import os
import sys

# git usurbs your bin path for hooks and will always run system python
site_packages = glob.glob('%s/lib/*/site-packages' % os.environ['VIRTUAL_ENV'])[0]
sys.path.insert(0, site_packages)

from flake8.main import git

STRICT = os.getenv('FLAKE8_STRICT', True)
LAZY = os.getenv('FLAKE8_LAZY', False)


if __name__ == '__main__':
    sys.exit(git.hook(
        strict=STRICT,
        lazy=LAZY,
        ))
