# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0002_auto_20160304_1703'),
        ('user', '0002_auto_20160307_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_project', to='user.GissmoUser')),
                ('sites', models.ManyToManyField(blank=True, to='place.Site')),
                ('users', models.ManyToManyField(blank=True, to='user.GissmoUser')),
            ],
        ),
    ]
