# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'intervention on equipment',
                'verbose_name_plural': 'Equipment interventions',
            },
        ),
        migrations.CreateModel(
            name='ActionSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transition', models.IntegerField(choices=[(0, 'Test failed'), (1, 'Test succeeded'), (2, 'Have a failure'), (3, 'Fixed')])),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'intervention on site',
                'verbose_name_plural': 'Site interventions',
            },
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InterventionPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.Intervention')),
            ],
        ),
    ]
