# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-21 08:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
        ('document', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiliation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=None)),
                ('documents', models.ManyToManyField(blank=True, to='document.Document')),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.Intervention')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliation.Organism')),
            ],
            options={
                'verbose_name': 'Organism (interv.)',
                'verbose_name_plural': 'Organisms (interv.)',
            },
        ),
        migrations.CreateModel(
            name='Protagonist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.Intervention')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Protagonist (interv.)',
                'verbose_name_plural': 'Protagonists (interv.)',
            },
        ),
        migrations.AddField(
            model_name='intervention',
            name='organisms',
            field=models.ManyToManyField(through='intervention.Operator', to='affiliation.Organism'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Place'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='protagonists',
            field=models.ManyToManyField(through='intervention.Protagonist', to=settings.AUTH_USER_MODEL),
        ),
    ]
