# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 07:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0001_initial'),
        ('intervention', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Place'),
        ),
    ]
