# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('place', '0001_initial'),
        ('intervention', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Player'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='players',
            field=models.ManyToManyField(through='intervention.InterventionPlayer', to='user.Player'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.Site'),
        ),
        migrations.AddField(
            model_name='actionsite',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.Intervention'),
        ),
        migrations.AddField(
            model_name='actionequipment',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.Intervention'),
        ),
    ]
