# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0002_auto_20160304_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionequipment',
            name='intervention',
        ),
        migrations.RemoveField(
            model_name='actionsite',
            name='intervention',
        ),
        migrations.RemoveField(
            model_name='interventionplayer',
            name='intervention',
        ),
        migrations.RemoveField(
            model_name='interventionplayer',
            name='player',
        ),
        migrations.AddField(
            model_name='intervention',
            name='confirmed',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='players',
            field=models.ManyToManyField(to='user.Player'),
        ),
        migrations.DeleteModel(
            name='ActionEquipment',
        ),
        migrations.DeleteModel(
            name='ActionSite',
        ),
        migrations.DeleteModel(
            name='InterventionPlayer',
        ),
    ]
