# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('intervention', '0002_auto_20160304_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActionEquipment',
        ),
        migrations.DeleteModel(
            name='ActionSite',
        ),
        migrations.RemoveField(
            model_name='interventionplayer',
            name='intervention',
        ),
        migrations.AddField(
            model_name='intervention',
            name='confirmed',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='intervention',
            name='documents',
            field=models.ManyToManyField(blank=True, to='document.Document'),
        ),
        migrations.DeleteModel(
            name='InterventionPlayer',
        ),
    ]
