# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 12:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('affiliation', '0001_initial'),
        ('intervention', '0002_intervention_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Organisms (interv.)',
                'verbose_name': 'Organism (interv.)',
            },
        ),
        migrations.CreateModel(
            name='Protagonist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Protagonists (interv.)',
                'verbose_name': 'Protagonist (interv.)',
            },
        ),
        migrations.RemoveField(
            model_name='intervention',
            name='operators',
        ),
        migrations.AddField(
            model_name='protagonist',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.Intervention'),
        ),
        migrations.AddField(
            model_name='protagonist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operator',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.Intervention'),
        ),
        migrations.AddField(
            model_name='operator',
            name='organism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliation.Organism'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='organisms',
            field=models.ManyToManyField(through='intervention.Operator', to='affiliation.Organism'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='protagonists',
            field=models.ManyToManyField(through='intervention.Protagonist', to=settings.AUTH_USER_MODEL),
        ),
    ]
